apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.pvcName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage | quote }}
