apiVersion: v1
kind: Secret
metadata:
  name: notes-mysql
  namespace: notes
type: Opaque
stringData:
  MYSQL_DATABASE: notesdb
  MYSQL_PASSWORD: notespass
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: notesuser
